-- DDL espelha as entidades JPA br.com.ecotransparencia.entity.Embargo e AutoInfracao.
-- Mapeamento: Long -> BIGINT, Integer -> INTEGER, LocalDateTime -> TIMESTAMP,
-- String sem length -> VARCHAR(255), String com @Column(length=N) -> VARCHAR(N),
-- BigDecimal monetario (val_auto_infracao) -> NUMERIC(15,2), BigDecimal area/coords -> NUMERIC(15,4).
-- PKs: seq_tad (embargo), seq_auto_infracao (auto_infracao). Sem indices alem da PK
-- (preserva o "no behavior change" da Fase A; indices em cpf_cnpj entrarao na Fase B).

CREATE TABLE embargo (
    seq_tad                 BIGINT PRIMARY KEY,
    num_tad                 VARCHAR(255),
    ser_tad                 VARCHAR(255),
    dat_embargo             TIMESTAMP,
    dat_ult_alteracao       TIMESTAMP,
    sig_uf_tad              VARCHAR(255),
    nom_municipio_tad       VARCHAR(255),
    num_longitude_tad       NUMERIC(15,4),
    num_latitude_tad        NUMERIC(15,4),
    nome_imovel             VARCHAR(255),
    des_localizacao_tad     VARCHAR(2000),
    nome_pessoa_embargada   VARCHAR(255),
    cpf_cnpj_embargado      VARCHAR(255),
    sit_desmatamento        VARCHAR(255),
    tp_area_embargada       VARCHAR(255),
    qtd_area_embargada      NUMERIC(15,4),
    operacao                VARCHAR(255),
    unid_ibama_controle     VARCHAR(255),
    num_processo            VARCHAR(255),
    des_tad                 VARCHAR(4000),
    num_auto_infracao       VARCHAR(255),
    ser_auto_infracao       VARCHAR(255),
    qtd_area_desmatada      NUMERIC(15,4),
    des_infracao            VARCHAR(4000),
    cod_tipo_bioma          INTEGER,
    des_tipo_bioma          VARCHAR(255),
    ind_baixado             VARCHAR(255)
);

CREATE TABLE auto_infracao (
    seq_auto_infracao               BIGINT PRIMARY KEY,
    num_auto_infracao               VARCHAR(255),
    ser_auto_infracao               VARCHAR(255),
    des_status_formulario           VARCHAR(255),
    ds_sit_auto_aie                 VARCHAR(255),
    sit_cancelado                   VARCHAR(255),
    tipo_auto                       VARCHAR(255),
    tipo_multa                      VARCHAR(255),
    val_auto_infracao               NUMERIC(15,2),
    fundamentacao_multa             VARCHAR(4000),
    gravidade_infracao              VARCHAR(255),
    cd_nivel_gravidade              VARCHAR(255),
    motivacao_conduta               VARCHAR(255),
    efeito_meio_ambiente            VARCHAR(255),
    efeito_saude_publica            VARCHAR(255),
    passivel_recuperacao            VARCHAR(255),
    des_auto_infracao               VARCHAR(4000),
    dat_hora_auto_infracao          TIMESTAMP,
    dat_ciencia_autuacao            TIMESTAMP,
    dt_fato_infracional             TIMESTAMP,
    cod_municipio                   INTEGER,
    municipio                       VARCHAR(255),
    uf                              VARCHAR(255),
    num_processo                    VARCHAR(255),
    cod_infracao                    INTEGER,
    des_infracao                    VARCHAR(500),
    tipo_infracao                   VARCHAR(255),
    tp_pessoa_infrator              VARCHAR(255),
    nome_infrator                   VARCHAR(255),
    cpf_cnpj_infrator               VARCHAR(255),
    qt_area                         NUMERIC(15,4),
    infracao_area                   VARCHAR(255),
    classificacao_area              VARCHAR(255),
    num_longitude                   NUMERIC(15,4),
    num_latitude                    NUMERIC(15,4),
    des_local_infracao              VARCHAR(2000),
    ds_biomas_atingidos             VARCHAR(255),
    operacao                        VARCHAR(255),
    dt_lancamento                   TIMESTAMP,
    dt_ult_alteracao                TIMESTAMP,
    ds_enquadramento_administrativo VARCHAR(500),
    ultima_atualizacao_relatorio    TIMESTAMP
);
